In [1]:
import pandas as pd
import numpy as np

import tensorflow as tf
import tensorflow.keras as tfk
from transformers import RobertaTokenizer, TFRobertaForTokenClassification

In [2]:
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
model = TFRobertaForTokenClassification.from_pretrained('roberta-base')

Some weights of the model checkpoint at roberta-base were not used when initializing TFRobertaForTokenClassification: ['lm_head']
- This IS expected if you are initializing TFRobertaForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing TFRobertaForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of TFRobertaForTokenClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['dropout_38', 'classifier']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [19]:
inputs = tokenizer("The dog don't want to go to the park", return_tensors="tf")
input_ids = inputs["input_ids"]
inputs["labels"] = tf.reshape(tf.constant([1] * tf.size(input_ids).numpy()), (-1, tf.size(input_ids))) # Batch size 1

In [20]:
outputs = model(inputs)
loss, scores = outputs[:2]

In [21]:
scores.numpy().argmax(axis=2)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0]], dtype=int64)

In [22]:
scores

<tf.Tensor: shape=(1, 12, 2), dtype=float32, numpy=
array([[[ 0.07320175, -0.13443092],
        [ 0.10711331, -0.02687809],
        [ 0.14315242,  0.01297282],
        [ 0.08094317,  0.01106001],
        [ 0.16553135,  0.14596383],
        [ 0.11580696, -0.03739508],
        [ 0.13648409, -0.12710442],
        [ 0.03800149, -0.01475356],
        [ 0.03861807, -0.00043664],
        [-0.03460314,  0.06129692],
        [ 0.00778822,  0.16512108],
        [ 0.04868036, -0.15220478]]], dtype=float32)>

In [24]:
tokenizer.decode(tf.boolean_mask(input_ids, scores.numpy().argmax(axis=2)))

' the park'